import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Cuprum, Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
 
const cuprum = Cuprum({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})



const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cuprum.className} style={{color:"white"}}>
      <body>
      <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
